runtime: nodejs10

env_variables:
  MONGODB_URI: 'mongodb+srv://tomekomel:nikon@cluster0.iwi3z.mongodb.net/decisions?retryWrites=true&w=majority'

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

