version: "3"

services:
  backend_service:
    depends_on:
      - db
    restart: always
    build: .
    ports:
    - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://db_mongo/decisions
    volumes:
    - .:/data/app
    - /data/app/node_modules

  db:
    image: mongo
    container_name: db_mongo
    volumes:
    - mongodata:/data/db
    ports:
    - "27077:27017"

volumes:
  mongodata:
